import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cài đặt',
  description: 'Generated by create next app'
};

export default function SettingLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
