import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Khóa học',
  description: 'Generated by create next app'
};

export default function CoursesLayout({ children }: { children: React.ReactNode }) {
  return <div className="container mx-auto">{children}</div>;
}
