import { MainLayout } from '@/components/layouts';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Chiến dịch',
  description: 'Generated by create next app'
};

export default function CampaignsLayout({ children }: { children: React.ReactNode }) {
  return (
    <MainLayout
      title="Phòng Solution"
      isBack={true}
      description="Test desc"
      edit={{ title: 'Edit campaign', href: '/' }}
      subtitle="Từ  24/02/2023 - 28/02/2023"
    >
      {children}
    </MainLayout>
  );
}
