import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Báo cáo',
  description: 'Generated by create next app'
};

export default function ReportLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
