import '@/styles/globals.scss';

import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import HeaderMain from './header';
import { DatePickerConfig } from '@/config/date-picker';
import { ELocale, getDictionary } from '@/utils/dictionaries';
import { ThemeProvider } from '@/components/Providers';

export const metadata: Metadata = {
  title: 'Trang chủ',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: ELocale };
}) {
  const messages = await getDictionary(params.locale);

  return (
    <html lang={params.locale} data-theme="light">
      <body id="__next" suppressHydrationWarning={true}>
        <ThemeProvider>
          <NextIntlClientProvider locale={params.locale} messages={messages}>
            <HeaderMain />
            <main>
              <DatePickerConfig>{children}</DatePickerConfig>
            </main>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
