import Image from 'next/image';
import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Trang không tồn tại',
  description: 'Generated by create next app'
};

export default async function NotFound() {
  return (
    <div className="lg:px-24 lg:py-24 md:py-20 md:px-44 px-4 py-24 items-center flex justify-center flex-col-reverse lg:flex-row md:gap-28 gap-16">
      <div className="xl:pt-24 w-full xl:w-1/2 relative pb-12 lg:pb-0">
        <div className="relative">
          <div className="absolute">
            <div className="">
              <h1 className="my-2 text-neutral font-bold text-2xl">
                Looks like youve found the doorway to the great nothing
              </h1>
              <p className="my-2 text-neutral">
                Sorry about that! Please visit our hompage to get where you need to go.
              </p>
              <button className="sm:w-full lg:w-auto my-2 rounded md py-4 px-8 text-center text-base-100 bg-gradient-to-l to-primary from-secondary outline-none">
                <Link href="/">Take me there!</Link>
              </button>
            </div>
          </div>
          <div>
            <Image src="/not-found/404.png" width={539} height={190} alt="404" />
          </div>
        </div>
      </div>
      <div>
        <Image width={539} height={400} src="/not-found/404-draw.png" alt="404-draw" />
      </div>
    </div>
  );
}
